### ISSUE TITLE
Question: How many extra space do I need when I run this tool?

### ISSUE THREAD

**Issue by wyncg** [dataegret/pgcompacttable#41]
I want to run this tool against a table on production database. I would like to know how many extra space I need when I run it.

I saw in the read me section, the space I need is `the size of the largest index`. I want to confirm couple things:
- If I skip reindex, does that mean I don't need any extra space?
- If I only compact table and skip reindex, will it still free my disk space from the bloated table?
- The tool first compact table, then reindex. So given this scenario: my table has a waste of 100GB, and my largest index is 20GB. Does that mean even if I dont have 20GB free space in the beginning, ideally after table is compacted and before reindex occurs, I should have 100GB extra disk space, and I can safely let the tool run reindex?

Thanks in advance!

**Comment by Melkij** [comment]
Hello

> If I skip reindex, does that mean I don't need any extra space?

Almost true. One fine day I processed a 100gb table, when there was only 1 or 2 last free gb.
We may still have some fluctuations as we doing additional WAL writes due to VACUUM and fake UPDATE's.

> If I only compact table and skip reindex, will it still free my disk space from the bloated table?

Yes.
(although I must mention that there is nothing we can do with bloat in TOAST)

> The tool first compact table, then reindex. So given this scenario: my table has a waste of 100GB, and my largest index is 20GB. Does that mean even if I dont have 20GB free space in the beginning, ideally after table is compacted and before reindex occurs, I should have 100GB extra disk space, and I can safely let the tool run reindex?

Ideally, yes. Thought I'd rather do multiple runs with different options just to be sure.

An example of a non-ideal world: we successfully processed the table, but VACUUM was not able to shrink heap as much as possible because of concurrent transactions (command has a hardcoded limit in this phase). Next vacuum (or autovacuum) will continue shrinking, but pgcompacttable will try reindex at this point.

**Comment by wyncg** [comment]
Thanks for the quick reply!

Then I guess what I should do is passing skip reindex flag and show reindex command flag so it only compact the table first. After that, I manually run reindex in psql directly, or maybe just run pgcompacttable again if disk space is freed by significant amount.

Will close the issue for now.

**Comment by wyncg** [comment]
Oh one more question

If the table is compacted without reindex, will it perform like there is no index at all, or it will be just a little bit slower? Or it depends?

We have a table size of 253 GB, with a toast table of 63 GB. For the table it has three index, size of which are 20 GB, 12 GB, and 8 GB. Toast table has 1 GB index as well...

**Comment by Melkij** [comment]
Reindex by itself is a separate part, without reindex we just skip this part.
During table processing we need to move multiple rows from the end of the table to the beginning. Indexes in postgresql stores physical addresses of tuples, so they will be updated too. Each index write adds some cost. Therefore, table processing will be slightly slowed down by each index on the table.

**Comment by wyncg** [comment]
Ok thanks for the clarification!
